[project]
name = "alexnotes"
version = "0.1.0"
description = "Personal blog with notes on ML, finance, and more"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "nbformat>=5.10.4",
]
