project:
  type: website
  output-dir: ../_site

website:
  title: "Alex's Notes"
  description: "Notas personales sobre Machine Learning, matemáticas y más"
  site-url: "http://alexnotes-blog-2026.s3-website-eu-west-1.amazonaws.com"

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "GitHub"
        href: https://github.com/AlexNitid/fabad_experimental

  page-footer:
    left: "Alex de la Puente"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    link-external-newwindow: true

execute:
  freeze: auto
  enabled: false
